src/Entity/Forum.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ForumRepository")
 */
class Forum
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Auteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Message;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->Message;
    }

    public function setMessage(string $Message): self
    {
        $this->Message = $Message;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

src/Controller/ForumController.php
<?php

namespace App\Controller;
use App\Entity\Forum;
use App\Entity\User;
use App\Form\PostForumType;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


/**
* @Route("/forum")
*/
class ForumController extends AbstractController
{

    /**
    * @Route("/", name="app_forum")
    */
    public function index()
    {

        $repository = $this->getDoctrine()->getRepository(Forum::class);
        $forum = $repository->findAll();


        return $this->render('forum/index.html.twig', [
            'forum' => $forum,
            'user' => $this->getUser()
        ]);
    }

    /**
     * @Route("/post/{forum}", name="post_unique")
     * @param Forum $forum
     *
     * @return Response
     */
    public function postunique(EntityManagerInterface $entityManager, Forum $forum)
    {
        $repository = $this->getDoctrine()->getRepository(Forum::class);

        $forumunique = $repository->findOneBy(
            ['id' => $forum],
        );
        return $this->render('forum/unique.html.twig', [
            'forum' => $forumunique
        ]);
    }

    
    /**
    * @Route("/creerpost", name="post_topic")
    */
    public function post(Request $request): Response
    {    
  
        $forum = new Forum();
        $form = $this->createForm(PostForumType::class, $forum);
        $form->handleRequest($request);
        $date = new \DateTime('@'.strtotime('now'));


        if ($form->isSubmitted() && $form->isValid()) {

            $forum->setAuteur($this->getUser());
            $forum->setDate($date);

         
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($forum);
            $entityManager->flush();

            // do anything else you need here, like send an email
            return $this->redirectToRoute('app_forum');

        }
        return $this->render('forum/post.html.twig', [
            'registrationForm' => $form->createView(),
        ]);
    }
}

templates/forum/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper" style="margin-top: 100px;">
    <h1 style="font-size: 250%">Forum de communauté</h1><br><br>

    <a  href="{{ path('post_topic')}}" class="connexion"> Poster un topic</a> <br><br>
    
    <h2 style="font-size: 250%">Liste des topics</h2><br><br>
    {% for forums in forum %}
    
        <a href="{{ path('post_unique', {forum: forums.id}) }}">{{forums.titre}}</a><p>, publié le {{forums.date|date("m/d/Y")}} par {{forums.auteur}}</p>
    {% endfor %}
</div>
{% endblock %}

templates/forum/post.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

   <div class="formulaire">
    <h1>Poster sur le forum</h1>
    {{ form_start(registrationForm) }}
     
        <div class="reste">
 
            {{ form_row(registrationForm.category, { 'attr': {'class': 'txtp'} }) }}    
            {{ form_row(registrationForm.Message, { 'attr': {'class': 'txtp'} }) }}    
            {{ form_row(registrationForm.Titre, { 'attr': {'class': 'txtp'} }) }}    

        </div>

        {{ form_row(registrationForm.save, { 'attr': {'class': 'connexion'} }) }}

     {{ form_end(registrationForm)   }}
    <p>Les champs suivis de * sont obligatoires </p>
    </div>
{% endblock %}

templates/forum/unique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ForumController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper" style="margin-top: 100px;">
    <h2 style="font-size: 250%">{{forum.titre}}</h2>
    <p>Posté le {{forum.date|date("m/d/Y")}} par {{forum.auteur}}</p>
    <p>{{forum.message}}</p>
    <a href="{{path('app_forum')}}">Retourner au forum</a>

</div>
{% endblock %}